const data = [
    {
        id: 1,
        title : "Washington Avenue", 
        location : "Nasirabad H/S, Chattogram" , 
        rent : 194, 
        img: "https://i.ibb.co/FYRLTw1/Rectangle-394.png",
        roomSnapp1 : "https://i.ibb.co/s69MgL5/Rectangle-410.png",
        roomSnapp2 : "https://i.ibb.co/njJ2vtH/Rectangle-407.png",
        roomSnapp3 : "https://i.ibb.co/z73MvHs/Rectangle-408.png",
        roomSnapp4 : "https://i.ibb.co/9w8kg6j/Rectangle-409.png",
        descriptions :"3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.",
        priceDetails : "Rent/Month: $550 (negotiable) Service Charge : 8,000/= Tk per month, subject to change Security Deposit : 3 month’s rent Flat Release Policy : 3 months earlier notice required",
        propertyDetails:"Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor : A5 (5th Floor) (6 storied Building ) (South Facing Unit) Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
    },
    {
        id: 2,
        title : "Family Apartment Three", 
        location : "Nasirabad H/S, Chattogram" , 
        rent : 356 , 
        img : "https://i.ibb.co/61BRpN3/Rectangle-396.png",
        roomSnapp1 : "https://i.ibb.co/s69MgL5/Rectangle-410.png",
        roomSnapp2 : "https://i.ibb.co/njJ2vtH/Rectangle-407.png",
        roomSnapp3 : "https://i.ibb.co/z73MvHs/Rectangle-408.png",
        roomSnapp4 : "https://i.ibb.co/9w8kg6j/Rectangle-409.png",
        descriptions :"3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.",
        priceDetails : "Rent/Month: $550 (negotiable) Service Charge : 8,000/= Tk per month, subject to change Security Deposit : 3 month’s rent Flat Release Policy : 3 months earlier notice required",
        propertyDetails:"Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor : A5 (5th Floor) (6 storied Building ) (South Facing Unit) Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
    },
    {
        id: 3,
        title : "Gorgeous house", 
        location : "Nasirabad H/S, Chattogram" , 
        rent : 256 , 
        img : "https://i.ibb.co/djRFhwR/Rectangle-398.png",
        roomSnapp1 : "https://i.ibb.co/s69MgL5/Rectangle-410.png",
        roomSnapp2 : "https://i.ibb.co/njJ2vtH/Rectangle-407.png",
        roomSnapp3 : "https://i.ibb.co/z73MvHs/Rectangle-408.png",
        roomSnapp4 : "https://i.ibb.co/9w8kg6j/Rectangle-409.png",
        descriptions :"3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.",
        priceDetails : "Rent/Month: $550 (negotiable) Service Charge : 8,000/= Tk per month, subject to change Security Deposit : 3 month’s rent Flat Release Policy : 3 months earlier notice required",
        propertyDetails:"Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor : A5 (5th Floor) (6 storied Building ) (South Facing Unit) Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
    },
    {
        id: 4,
        title : "Luxury villa", 
        location : "Nasirabad H/S, Chattogram" , 
        rent : 345 , 
        img : "https://i.ibb.co/GdJnpPt/Rectangle-403.png",
        roomSnapp1 : "https://i.ibb.co/s69MgL5/Rectangle-410.png",
        roomSnapp2 : "https://i.ibb.co/njJ2vtH/Rectangle-407.png",
        roomSnapp3 : "https://i.ibb.co/z73MvHs/Rectangle-408.png",
        roomSnapp4 : "https://i.ibb.co/9w8kg6j/Rectangle-409.png",
        descriptions :"3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.",
        priceDetails : "Rent/Month: $550 (negotiable) Service Charge : 8,000/= Tk per month, subject to change Security Deposit : 3 month’s rent Flat Release Policy : 3 months earlier notice required",
        propertyDetails:"Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor : A5 (5th Floor) (6 storied Building ) (South Facing Unit) Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
    },
    {
        id: 5,
        title : "Epic Huda Palacio", 
        location : "Nasirabad H/S, Chattogram" , 
        rent : 536 , 
        img: "https://i.ibb.co/M7Ytbc1/Rectangle-404.png",
        roomSnapp1 : "https://i.ibb.co/s69MgL5/Rectangle-410.png",
        roomSnapp2 : "https://i.ibb.co/njJ2vtH/Rectangle-407.png",
        roomSnapp3 : "https://i.ibb.co/z73MvHs/Rectangle-408.png",
        roomSnapp4 : "https://i.ibb.co/9w8kg6j/Rectangle-409.png",
        descriptions :"3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.",
        priceDetails : "Rent/Month: $550 (negotiable) Service Charge : 8,000/= Tk per month, subject to change Security Deposit : 3 month’s rent Flat Release Policy : 3 months earlier notice required",
        propertyDetails:"Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor : A5 (5th Floor) (6 storied Building ) (South Facing Unit) Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
    },
    {
        id: 6,
        title : "Washington Avenue", 
        location : "Nasirabad H/S, Chattogram" , 
        rent : 283, 
        img: "https://i.ibb.co/fCtMXgY/Rectangle-405.png",
        roomSnapp1 : "https://i.ibb.co/s69MgL5/Rectangle-410.png",
        roomSnapp2 : "https://i.ibb.co/njJ2vtH/Rectangle-407.png",
        roomSnapp3 : "https://i.ibb.co/z73MvHs/Rectangle-408.png",
        roomSnapp4 : "https://i.ibb.co/9w8kg6j/Rectangle-409.png",
        descriptions :"3000 sq-ft., 3 Bedroom, Semi-furnished, Luxurious, South facing Apartment for Rent in Rangs Malancha, Melbourne.",
        priceDetails : "Rent/Month: $550 (negotiable) Service Charge : 8,000/= Tk per month, subject to change Security Deposit : 3 month’s rent Flat Release Policy : 3 months earlier notice required",
        propertyDetails:"Address & Area : Rangs Malancha, House-68, Road-6A (Dead End Road), Dhanmondi Residential Area. Flat Size : 3000 Sq Feet. Floor : A5 (5th Floor) (6 storied Building ) (South Facing Unit) Room Category : 3 Large Bed Rooms with 3 Verandas, Spacious Drawing, Dining & Family Living Room, Highly Decorated Kitchen with Store Room and Servant room with attached Toilet. Facilities : 1 Modern Lift, All Modern Amenities & Semi Furnished. Additional Facilities : a. Electricity with full generator load, b. Central Gas Geyser, c. 2 Car Parking with 1 Driver’s Accommodation, d. Community Conference Hall, e. Roof Top Beautified Garden and Grassy Ground, f. Cloth Hanging facility with CC camera"
    }
    ]
    export default data;